#!/usr/bin/env bash
#
# lib/makeconf.sh - Generate optimized make.conf
#

# Generate CFLAGS based on arch and optimization level
generate_cflags() {
    local arch="$1"
    local opt_level="${OPTIMIZATION_LEVEL:-O2}"
    local extra="${CFLAGS_EXTRA:-}"

    local base
    case "$arch" in
        amd64)
            base="native"
            ;;
        aarch64)
            base="armv8-a+crc+crypto"
            ;;
        *)
            base="native"
            ;;
    esac

    # Platform-specific adjustments
    if [[ "$PLATFORM" == "laptop" ]]; then
        opt_level="${opt_level}"
    fi

    local cflags="-march=${base} -${opt_level} -pipe"

    # Laptop: slightly less aggressive for battery
    if [[ "$PLATFORM" == "laptop" ]]; then
        cflags="${cflags} -fomit-frame-pointer"
    fi

    # Add extra flags
    if [[ -n "$extra" ]]; then
        cflags="${cflags} ${extra}"
    fi

    echo "$cflags"
}

# Generate MAKEOPTS based on CPU cores
generate_makeopts() {
    local config="$MAKEOPTS"

    if [[ "$config" == "auto" ]]; then
        local cores
        cores=$(get_cpu_cores)
        echo "-j$((cores + 1))"
    else
        echo "$config"
    fi
}

# Generate EMERGE_DEFAULT_OPTS
generate_emerge_opts() {
    local opts=""

    # Parallel fetching
    opts="--jobs=$(get_cpu_cores) --load-average=$(get_cpu_cores)"

    if [[ -n "$EMERGE_DEFAULT_OPTS_EXTRA" ]]; then
        opts="${opts} ${EMERGE_DEFAULT_OPTS_EXTRA}"
    fi

    echo "$opts"
}

# Generate complete make.conf
generate_make_conf() {
    local arch="$1"
    local root="${GENTOO_ROOT:-/mnt/gentoo}"

    local cflags
    cflags=$(generate_cflags "$arch")

    local makeopts
    makeopts=$(generate_makeopts)

    local emerge_opts
    emerge_opts=$(generate_emerge_opts)

    local cpu_flags_var="${CPU_FLAGS_VAR:-CPU_FLAGS_X86}"
    local cpu_flags="${CPU_FLAGS_DETECTED:-$CPU_FLAGS_DEFAULT}"

    # Build profile path
    local profile_path
    profile_path=$(get_profile_path "$arch")

    cat > "${root}/etc/portage/make.conf" << MAKECONF
# ============================================================
# Gentoo make.conf - Generated by gentoo-script
# Architecture: $arch
# Platform: $PLATFORM
# Init: $INIT_SYSTEM
# ============================================================

# Optimization flags
CFLAGS="${cflags}"
CXXFLAGS="${cflags}"
FCFLAGS="${cflags}"
FFLAGS="${cflags}"

# Build parallelism
MAKEOPTS="${makeopts}"

# CPU flags
${cpu_flags_var}="${cpu_flags}"

# Portage profile
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# Sync
GENTOO_MIRRORS="https://distfiles.gentoo.org"
GRUB_PLATFORMS="${GRUB_PLATFORMS:-efi-64 pc}"

# Emerge defaults
EMERGE_DEFAULT_OPTS="${emerge_opts}"

# License
ACCEPT_LICENSE="-* @FREE"
MAKECONF

    # Append USE flags if set
    if [[ -n "$USE_ADD" ]] || [[ -n "$USE_REMOVE" ]]; then
        local use_flags=""
        if [[ -n "$USE_ADD" ]]; then
            use_flags="$USE_ADD"
        fi
        if [[ -n "$USE_REMOVE" ]]; then
            use_flags="${use_flags} ${USE_REMOVE}"
        fi
        echo "" >> "${root}/etc/portage/make.conf"
        echo "# USE flags" >> "${root}/etc/portage/make.conf"
        echo "USE=\"${use_flags}\"" >> "${root}/etc/portage/make.conf"
    fi

    # Append license accept if set
    if [[ -n "$LICENSE_ACCEPT" ]]; then
        echo "" >> "${root}/etc/portage/make.conf"
        echo "# Additional licenses" >> "${root}/etc/portage/make.conf"
        echo "ACCEPT_LICENSE=\"${LICENSE_ACCEPT}\"" >> "${root}/etc/portage/make.conf"
    fi

    log_info "Generated make.conf at ${root}/etc/portage/make.conf"
}

# Get profile path for arch + init + desktop
get_profile_path() {
    local arch="$1"
    local profile_base

    case "$arch" in
        amd64)
            profile_base="default/linux/amd64"
            ;;
        aarch64)
            profile_base="default/linux/arm64"
            ;;
    esac

    local suffix
    case "$INIT_SYSTEM" in
        systemd)
            suffix="/systemd"
            ;;
        *)
            suffix=""
            ;;
    esac

    if [[ "$INSTALL_DESKTOP" == "yes" ]]; then
        case "$DESKTOP_ENV" in
            gnome)
                suffix="${suffix}/gnome"
                ;;
            kde)
                suffix="${suffix}/kde"
                ;;
            xfce)
                suffix="${suffix}/xfce"
                ;;
            *)
                suffix="${suffix}/desktop"
                ;;
        esac
    else
        suffix="${suffix}/server"
    fi

    echo "${profile_base}${suffix}"
}

# Set profile
set_profile() {
    local arch="$1"
    local profile_path
    profile_path=$(get_profile_path "$arch")

    log_info "Setting Portage profile: $profile_path"
    chroot_run "eselect profile set '${profile_path}'" || {
        log_warn "Could not set profile automatically, trying to match..."
        chroot_run "eselect profile list"
        chroot_run "eselect profile set '${profile_path}'" || die "Failed to set profile"
    }
}
